Use lcov instead of simplecov to send coverage to CodeClimate
Using simplecov format causes the following error.

> Error: json: cannot unmarshal object into Go struct field
> resultSet.coverage of type []formatters.NullInt